### ISSUE TITLE
请提供ST77903示例压缩包

### ISSUE THREAD

**Issue by modi12jin** [Lzw655/esp32-s3-lcd-ev-baord-docs#2]
> QSPI 接口没有正式的通用驱动及示例，目前仅针对 ST77903 的 QSPI 接口进行了适配，如用户有需求可以提供示例压缩包

@Lzw655 你好！ 我想问一下，如何获取你的示例压缩包？ 我正在使用ST77903这个不带GRAM的奇葩屏幕，我成功初始化，希望有你的示例代码指导我后续工作。

![IMG_20230312_235447](https://user-images.githubusercontent.com/40233017/228848258-a8807cdb-6be5-4c7e-95f5-f639ef5b102d.jpg)

> 淘宝购买链接

![tb_image_share_1689678031936](https://github.com/Lzw655/esp32-s3-lcd-ev-baord-docs/assets/40233017/57d958d4-7eef-46e9-b2c1-782b2edefe1c)

[1870074967H0165Y005T005B+V0规格书.pdf](https://github.com/Lzw655/esp32-s3-lcd-ev-baord-docs/files/11412687/1870074967H0165Y005T005B%2BV0.pdf)

**Comment by Lzw655** [comment]
@modi12jin 你好，这个 QSPI 的驱动目前仅供测试，还未完善释放，而且依赖了了 ESP-IDF 的一些未合入的新特性，所以需要在最新的 master 分支打上补丁（见 patch 目录），驱动仅适配 ESP32-S3R2/8、ESP32-C6
如需技术支持，请联系乐鑫官方商务。
[ST77903_QSPI_1_3_320_320.zip](https://github.com/Lzw655/esp32-s3-lcd-ev-baord-docs/files/11118306/ST77903_QSPI_1_3_320_320.zip)

**Comment by modi12jin** [comment]
感谢你的回复，这将是目前QSPI最好参考。

**Comment by Lzw655** [comment]
https://github.com/espressif/esp-idf/issues/11787#issuecomment-1622838282

Here is the newest driver and example.
