### ISSUE TITLE
QSPI屏幕推荐

### ISSUE THREAD

**Issue by modi12jin** [Lzw655/esp32-s3-lcd-ev-baord-docs#3]
SPD2010是目前为止性价比最高的屏幕，因为它是LCD+in-cell+TDDI，该IC集成了RAM和自电容 incell 触摸控制器。

> 屏幕官方介绍

https://www.solomon-systech.com/solomon-systech-launches-spd2010-for-1st-full-color-tddi-in-wearable-display/

> 淘宝购买渠道

![tb_image_share_1689677879720](https://github.com/Lzw655/esp32-s3-lcd-ev-baord-docs/assets/40233017/2fdc671a-47f9-4222-8dd8-550f58fd4c14)

[SPD2010.zip](https://github.com/Lzw655/esp32-s3-lcd-ev-baord-docs/files/11414818/SPD2010.zip)

[2080832853H0146Y005T005A+V0规格书1.45寸412X412+QSPI_1.pdf](https://github.com/Lzw655/esp32-s3-lcd-ev-baord-docs/files/12813528/2080832853H0146Y005T005A%2BV0.1.45.412X412%2BQSPI_1.pdf)

> 它的触摸地址：0x53或者0xD3

**Comment by Lzw655** [comment]
好的，感谢分享

**Comment by modi12jin** [comment]
![Share_Screenshot_1684676885199404187358081981224](https://github.com/Lzw655/esp32-s3-lcd-ev-baord-docs/assets/40233017/da8900c3-8e5c-42cf-b6fd-fe7881e2240a)

我找到方屏版本SPD2012

**Comment by modi12jin** [comment]
![tb_image_share_1684754043602](https://github.com/Lzw655/esp32-s3-lcd-ev-baord-docs/assets/40233017/8d1e9c34-3f7a-4690-b492-379536bc086b)

如果使用方屏QSPI可以使用这个屏幕SPD2012(WEA2012)

https://www.osptek.com/products/1/4/143

[1.72"_356*400_WEA2012.txt](https://github.com/Lzw655/esp32-s3-lcd-ev-baord-docs/files/12316326/1.72._356.400_WEA2012.txt)

> 有可能这个仓库值的参考

https://github.com/moyitai/6.11_tease_code/blob/master/cpu/br28/ui_driver/lcd_drive/lcd_spi/lcd_spi_L_WEA2012_356x400.c

[ESP32S3_WEA2012.txt](https://github.com/Lzw655/esp32-s3-lcd-ev-baord-docs/files/12315694/ESP32S3_WEA2012.txt)

> 视频演示

https://www.youtube.com/shorts/ooH_w3yC7S8

https://www.youtube.com/shorts/Q7KiyiYLQjA

> 拓淘电子

[拓淘电子_WEA2012.zip](https://github.com/Lzw655/esp32-s3-lcd-ev-baord-docs/files/13165929/_WEA2012.zip)
